{% set name = "onnxmltools" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/onnxmltools/archive/{{ version }}.tar.gz
  sha256: 172449d8e20f50ef15e60f0896fd9a21a1ec37ba76d7f26e1cac2fce99198daa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - keras2onnx
    - numpy
    - onnx
    - onnxconverter-common >=1.8,<1.9
    - protobuf
    - skl2onnx

test:
  imports:
    - onnxmltools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
