{% set name = "onnxmltools" %}
{% set version = "1.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/onnxmltools-{{ version }}.tar.gz
    sha256: 4348cc1385cb48c6e527b20ef0da4d80dcbe10f95ddc4ecd66d6b57f9ac159be
  - url: https://raw.githubusercontent.com/onnx/onnxmltools/v{{ version }}/requirements.txt
    sha256: 2e8729f47e8d7c09fa1b7d5f7de86f24ec05e92b921192bc4ece0086b3979450
    fn: requirements.txt

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy 
    - onnx 
    - skl2onnx 

test:
  imports:
    - onnxmltools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
