{% set name = "onnxmltools" %}
{% set version = "1.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/onnxmltools-{{ version }}.tar.gz
    sha256: ebdc529a78ce79c4be767cd6535544f983fe9dc0ca10f434194086f1c5be64d1
  - url: https://raw.githubusercontent.com/onnx/onnxmltools/{{ version }}/requirements.txt
    sha256: f92d283a3e3737a71589af98ef83d528fd8d6f104b11fde77da04c3a8c38d897
    fn: requirements.txt

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy 
    - onnx 
    - skl2onnx

test:
  imports:
    - onnxmltools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/onnxmltools
  summary: ONNXMLTools enables conversion of models to ONNX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
    - janjagusch
